'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sentinel', {
  locateAdb: () => ipcRenderer.invoke('adb:locate'),
  deviceSummary: () => ipcRenderer.invoke('device:summary'),
  disableUsbDebugging: () => ipcRenderer.invoke('usb:disable'),
  exportPng: (rect) => ipcRenderer.invoke('export:png', rect),
  isStale: () => ipcRenderer.invoke('app:stale'),
  runChecks: () => ipcRenderer.invoke('checks:run'),
  onCheckResult: (cb) => ipcRenderer.on('checks:result', (_e, r) => cb(r)),
  listProposals: () => ipcRenderer.invoke('proposals:list'),
  disablePackages: (pkgs) => ipcRenderer.invoke('proposals:disable', pkgs),
  enablePackage: (pkg) => ipcRenderer.invoke('proposals:enable', pkg),
  enablePackages: (pkgs) => ipcRenderer.invoke('proposals:enableMany', pkgs),
  listHistory: () => ipcRenderer.invoke('history:list'),
  revertAll: () => ipcRenderer.invoke('actions:revertAll'),
  trustSideloads: (pkgs) => ipcRenderer.invoke('sideloads:trust', pkgs),
  searchWeb: (q) => ipcRenderer.invoke('open:search', q),
  openUrl: (u) => ipcRenderer.invoke('open:url', u),
  deviceDetails: () => ipcRenderer.invoke('device:details'),
  listApps: () => ipcRenderer.invoke('apps:list'),
  permsAudit: () => ipcRenderer.invoke('perms:audit'),
  verifyApp: (pkg) => ipcRenderer.invoke('apps:verify', pkg),
  setBattery: (pkgs, mode) => ipcRenderer.invoke('battery:set', { pkgs, mode }),
  revertBattery: () => ipcRenderer.invoke('battery:revert'),
  listSettings: () => ipcRenderer.invoke('settings:list'),
  applySettings: (keys) => ipcRenderer.invoke('settings:apply', keys),
  revertSettings: () => ipcRenderer.invoke('settings:revert'),
  termLibrary: () => ipcRenderer.invoke('term:library'),
  termClassify: (cmd) => ipcRenderer.invoke('term:classify', cmd),
  termRun: (cmd) => ipcRenderer.invoke('term:run', cmd),
  onAdbLog: (cb) => ipcRenderer.on('adb:log', (_e, entry) => cb(entry)),
  recentLog: () => ipcRenderer.invoke('log:recent'),
  openLogFile: () => ipcRenderer.invoke('log:openFile'),
  openLogFolder: () => ipcRenderer.invoke('log:openFolder'),
  exportSave: (payload) => ipcRenderer.invoke('export:save', payload),
  readCredits: () => ipcRenderer.invoke('credits:read'),
  originAll: () => ipcRenderer.invoke('origin:all'),
  originOne: (pkg) => ipcRenderer.invoke('origin:one', pkg),
  snapshotsList: () => ipcRenderer.invoke('snapshots:list'),
  snapshotSave: (label) => ipcRenderer.invoke('snapshots:save', label),
  snapshotDelete: (id) => ipcRenderer.invoke('snapshots:delete', id),
  snapshotsCompare: (a, b) => ipcRenderer.invoke('snapshots:compare', { a, b }),
  snapshotsFolder: () => ipcRenderer.invoke('snapshots:openFolder'),
  snapshotRead: (id) => ipcRenderer.invoke('snapshots:read', id),
  snapshotRename: (id, label) => ipcRenderer.invoke('snapshots:rename', { id, label }),
  snapshotReveal: (id) => ipcRenderer.invoke('snapshots:revealFile', id),
  hardware: () => ipcRenderer.invoke('hw:read'),
  hardwareLive: () => ipcRenderer.invoke('hw:live'),
  permsApply: (groupId, mode, items) => ipcRenderer.invoke('perms:apply', { groupId, mode, items }),
  permsRevert: () => ipcRenderer.invoke('perms:revert'),
  exportReport: (includePersonal) => ipcRenderer.invoke('report:export', { includePersonal }),
  revealReport: (folder) => ipcRenderer.invoke('report:reveal', folder),
  onReportProgress: (cb) => ipcRenderer.on('report:progress', (_e, p) => cb(p)),
  platform: process.platform,
  onConfirmClose: (cb) => ipcRenderer.on('app:confirm-close', () => cb()),
  confirmQuit: () => ipcRenderer.invoke('app:confirmQuit'),
});
